exclude: ".venv|__pycache__|tests/dev/|tests/fixtures/"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=500
      - id: check-case-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args:
          - --remove
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      - id: ruff
        args:
          - --fix
          - --target-version=py39
      - id: ruff-format

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        files: ^lantmateriet/.*\.py$
        additional_dependencies:
          - flake8-qgis<2
        args:
          [
            "--select=QGS101,QGS102,QGS103,QGS104,QGS106",
          ]

ci:
    autoupdate_schedule: quarterly
    skip: []
    submodules: false
