name: "Build & Release"

on:
  push:
    branches:
      - main
      - ci/*
    paths:
      - .github/workflows/build-release.yml
      - "lantmateriet_qgis/**/*."
    tags:
      - "*"

jobs:
  translation:
    name: "Translation compilation"
    runs-on: ubuntu-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install translation requirements
        run: |
          sudo apt update
          sudo apt install qt5-qmake qttools5-dev-tools

      - name: Update translations
        run: uvx --with-requirements requirements/packaging.txt --from pyqt5-tools --python 3.11 pylupdate5 -noobsolete -verbose lantmateriet_qgis/resources/i18n/plugin_translation.pro

      - name: Compile translations
        run: lrelease lantmateriet_qgis/resources/i18n/*.ts

      - uses: actions/upload-artifact@v4
        with:
          name: translations-build
          path: lantmateriet_qgis/**/*.qm
          if-no-files-found: error
          retention-days: 5

  # -- NO TAGS ----------------------------------------------------------------------
  packaging:
    name: "Packaging plugin"
    runs-on: ubuntu-latest
    needs: [translation]

    if: ${{ !startsWith(github.ref, 'refs/tags/') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Download translations
        uses: actions/download-artifact@v5
        with:
          name: translations-build
          path: lantmateriet_qgis
      - name: Amend gitignore to include compiled translations and add it to tracked files
        run: |
          # include compiled translations
          sed -i "s|^*.qm.*| |" .gitignore

          # git add full project
          git add lantmateriet_qgis/

      - name: Package the latest version
        run: uvx --with-requirements requirements/packaging.txt --python 3.11 qgis-plugin-ci package latest --allow-uncommitted-changes

      - name: Extract version from metadata
        id: get_version
        run: |
          # Extract version from metadata.txt
          version=$(grep -oP '(?<=^version=).*' lantmateriet_qgis/metadata.txt)
          echo "VERSION=$version" >> $GITHUB_ENV
      - name: Unzip contents
        run: |
          mv lantmateriet_qgis lantmateriet_qgis.backup
          unzip lantmateriet_qgis.$VERSION.zip -d lantmateriet_qgis
      - uses: actions/upload-artifact@v4
        with:
          name: lantmateriet_qgis.${{ env.VERSION }}
          path: lantmateriet_qgis
          if-no-files-found: error

  # -- ONLY TAGS ----------------------------------------------------------------------
  release:
    name: "Release on tag"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [translation]

    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Download translations
        uses: actions/download-artifact@v5
        with:
          name: translations-build
          path: lantmateriet_qgis

      - name: Amend gitignore to include compiled translations and add it to tracked files
        run: |
          # include compiled translations
          sed -i "s|^*.qm.*| |" .gitignore

          # git add full project
          git add lantmateriet_qgis/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true

      - name: Deploy plugin
        run: >-
          uvx --with-requirements requirements/packaging.txt --python 3.11
          qgis-plugin-ci
          release ${GITHUB_REF/refs\/tags\//}
          --allow-uncommitted-changes
          --create-plugin-repo
          --github-token ${{ secrets.GITHUB_TOKEN }}
          --osgeo-username ${{ secrets.OSGEO_USER }}
          --osgeo-password ${{ secrets.OSGEO_PASSWORD }}
