name: "Build & Release"

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-release.yml
      - 'docs/**/*'
      - "lantmateriet/**/*.py"
      - "lantmateriet/metadata.txt"
      - "lantmateriet/resources/**/*"
    tags: 
      - "*"

jobs:
  translation:
    name: "Translation compilation"
    runs-on: ubuntu-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install translation requirements
        run: |
          sudo apt update
          sudo apt install qt5-qmake qttools5-dev-tools

      - name: Update translations
        run: uvx --with-requirements requirements/packaging.txt --from pyqt5-tools --python 3.11 pylupdate5 -noobsolete -verbose lantmateriet/resources/i18n/plugin_translation.pro

      - name: Compile translations
        run: lrelease lantmateriet/resources/i18n/*.ts

      - uses: actions/upload-artifact@v4
        with:
          name: translations-build
          path: lantmateriet/**/*.qm
          if-no-files-found: error

  # -- NO TAGS ----------------------------------------------------------------------
  packaging:
    name: "Packaging plugin"
    runs-on: ubuntu-latest
    needs: [translation]

    if: ${{ !startsWith(github.ref, 'refs/tags/') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Download translations
        uses: actions/download-artifact@v4
        with:
          name: translations-build
          path: lantmateriet
      - name: Amend gitignore to include compiled translations and add it to tracked files
        run: |
          # include compiled translations
          sed -i "s|^*.qm.*| |" .gitignore

          # git add full project
          git add lantmateriet/

      - name: Package the latest version
        run: uvx --with-requirements requirements/packaging.txt --python 3.11 qgis-plugin-ci package latest --allow-uncommitted-changes

      - uses: actions/upload-artifact@v4
        with:
          name: lantmateriet-latest
          path: lantmateriet.*.zip
          if-no-files-found: error

  # -- ONLY TAGS ----------------------------------------------------------------------
  release:
    name: "Release on tag"
    runs-on: ubuntu-latest    
    permissions:
      contents: write
    needs: [translation]

    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Download translations
        uses: actions/download-artifact@v4
        with:
          name: translations-build
          path: lantmateriet

      - name: Amend gitignore to include compiled translations and add it to tracked files
        run: |
          # include compiled translations
          sed -i "s|^*.qm.*| |" .gitignore

          # git add full project
          git add lantmateriet/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true

      - name: Deploy plugin
        run: >-
          uvx --with-requirements requirements/packaging.txt --python 3.11
          qgis-plugin-ci
          release ${GITHUB_REF/refs\/tags\//}
          --allow-uncommitted-changes
          --create-plugin-repo
          --github-token ${{ secrets.GITHUB_TOKEN }}
          --osgeo-username ${{ secrets.OSGEO_USER }}
          --osgeo-password ${{ secrets.OSGEO_PASSWORD }}
