name: "Tester"

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - .github/workflows/tester.yml
      - requirements/testing.txt

  pull_request:
    branches:
      - main
    paths:
      - '**.py'
      - .github/workflows/tester.yml
      - requirements/testing.txt

env:
  PROJECT_FOLDER: "lantmateriet"
  PYTHON_VERSION: 3.9


jobs:
  tests-unit:
    runs-on: ubuntu-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Run Unit tests
        run: uvx --with-requirements requirements/testing.txt pytest -p no:qgis tests/unit/

  test-qgis:
    runs-on: ubuntu-latest
    if: false

    container:
      image: qgis/qgis:release-3_28
      env:
        CI: true
        DISPLAY: ":1"
        MUTE_LOGS: true
        NO_MODALS: 1
        PYTHONPATH: "/usr/share/qgis/python/plugins:/usr/share/qgis/python:."
        QT_QPA_PLATFORM: "offscreen"
        WITH_PYTHON_PEP: false
        options: -v /tmp/.X11-unix:/tmp/.X11-unix -v ${{ github.workspace }}:/tests_directory

    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Print QGIS version
        run: qgis --version

      - name: Setup plugin
        run: qgis_setup.sh lantmateriet


      - name: Install Python requirements
        run: |
          python3 -m pip install -U pip setuptools wheel
          python3 -m pip install -U -r requirements/testing.txt

      - name: Run Unit tests
        run: |
          Xvfb :1 &
          python3 -m pytest tests/qgis/

